source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'AlertPro_Example', :exclusive => true do
  pod "AlertPro", :path => "../"
end

target 'AlertPro_Tests', :exclusive => true do
  pod "AlertPro", :path => "../"

  
end
